from enum import Enum
class Model(Enum):
    ANALOG = ("analog-diffusion-1.0.ckpt", "Analog V1", "01")
    ANYTHING_V3 = ("anythingv3_0-pruned.ckpt", "Anything V3", "02")
    ANYTHING_V4 = ("anything-v4.5-pruned.ckpt", "Anything V4.5", "03")
    ABYSSORANGEMIX = ("AOM3A3_orangemixs.safetensors", "AbyssOrangeMix V3", "04")
    DELIBERATE = ("deliberate_v2.safetensors", "Deliberate V2", "05")
    DREAMLIKE_V1 = ("dreamlike-diffusion-1.0.safetensors", "Dreamlike Diffusion V1", "06")
    DREAMLIKE_V2 = ("dreamlike-diffusion-2.0.safetensors", "Dreamlike Diffusion V2", "07")
    DREAMSHAPER_5 = ("dreamshaper_5BakedVae.safetensors", "Dreamshaper 5 baked vae", "08")
    DREAMSHAPER_6 = ("dreamshaper_6BakedVae.safetensors", "Dreamshaper 6 baked vae", "09")
    ELLDRETHVIVIDMIX = ("elldreths-vivid-mix.safetensors", "Elldreth's Vivid", "10")
    LYRIEL_V15 = ("lyriel_v15.safetensors", "Lyriel V1.5", "11")
    LYRIEL_V16 = ("lyriel_v16.safetensors", "Lyriel V1.6", "12")
    MECHAMIX = ("mechamix_v10.safetensors", "MechaMix V1.0", "13")
    MEINAMIX = ("meinamix_meinaV9.safetensors", "MeinaMix V9", "14")
    OPENJOURNEY = ("openjourney_V4.ckpt", "Openjourney V4", "15")
    PORTRAIT = ("portrait+1.0.safetensors", "Portrait V1", "16")
    REALISTICVS_V14 = ("Realistic_Vision_V1.4-pruned-fp16.safetensors", "Realistic Vision V1.4", "17")
    REALISTICVS_V20 = ("Realistic_Vision_V2.0.safetensors", "Realistic Vision V2.0", "18")
    REV_ANIMATED = ("revAnimated_v122.safetensors", "ReV Animated V1.2.2", "19")
    RIFFUSION = ("riffusion-model-v1.ckpt", "Riffusion V1", "20")
    SD_V14 = ("sdv1_4.ckpt", "Stable Diffusion V1.4", "21")
    SD_V15 = ("v1-5-pruned-emaonly.ckpt", "Stable Diffusion V1.5", "22")
    SBP = ("shoninsBeautiful_v10.safetensors", "Shonin's Beautiful People V1.0", "23")
    THEALLYSMIX = ("theallys-mix-ii-churned.safetensors", "TheAlly's Mix II", "24")
    TIMELESS = ("timeless-1.0.ckpt", "Timeless V1", "25")

class Ratio(Enum):
    SQUARE = ('square', "01")
    PORTRAIT = ('portrait', "02")
    LANDSCAPE = ('landscape', "03")

class Control(Enum):
    SOFT_EDGE = ("control_v11p_sd15_softedge", "Soft Edge", "01")
    MLSD = ("control_v11p_sd15_mlsd", "MLSD", "02")
    IP2P = ("control_v11e_sd15_ip2p", "IP2P", "03")
    SEG = ("control_v11p_sd15_seg", "Segmentation", "04")
    INPAINT = ("control_v11p_sd15_inpaint", "Inpaint", "05")
    LINEART_ANIME = ("control_v11p_sd15s2_lineart_anime", "Line Art Anime", "06")
    SHUFFLE = ("control_v11e_sd15_shuffle", "Shuffle", "07")
    CANNY = ("control_v11p_sd15_canny", "Canny", "08")
    LINEART = ("control_v11p_sd15_lineart", "Line Art", "09")
    NORMALBAE = ("control_v11p_sd15_normalbae", "Normal BAE", "10")
    DEPTH = ("control_v11f1p_sd15_depth", "Depth", "11")
    OPENPOSE = ("control_v11p_sd15_openpose", "Open Pose", "12")
    TILE = ("control_v11f1e_sd15_tile", "Tile", "13")
    SCRIBBLE = ("control_v11p_sd15_scribble", "Scribble", "14")

class Sampler(Enum):
    EULER = ("Euler", "01")
    EULER_A = ("Euler a", "02")
    HEUN = ("Heun", "03")
    DPM_2M_KARRAS = ("DPM++ 2M Karras", "04")
    DPM_SDE_KARRAS = ("DPM++ SDE Karras", "05")
    DDIM = ("DDIM", "06")
